name: Docs

on:
  push:
    branches: [source]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install rust
        run: rustup update

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.3.7"

      - name: Install skill-tree
        run: cargo install --vers "^1.3.1" skill-tree

      - name: Generate book
        run: mdbook build

      - name: Generate roadmap
        run: skill-tree roadmap.toml book

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: book
